### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by hrak109** [RockyLim92/os-fall-2018#3]
![bqonq4dytw6xqaulchur9w](https://user-images.githubusercontent.com/14815888/45350910-e181ee00-b5ef-11e8-88bb-02bc35318cf6.jpg)

I'm using vm ubuntu 16.04.5, and I've followe all instructions up to here.

**Comment by shastakr** [comment]
Same for me

**Comment by mr3coi** [comment]
Same here

**Comment by mr3coi** [comment]
Same here, with a newly-installed Ubuntu 16.04

**Comment by RockyLim92** [comment]
커널 소스에 변경된 사항이 있어 업데이트 하였습니다. 기존의 커널 소스 디렉토리에서 다음과 같은 명령어로 새롭게 clone을 하여 코드를 받아 빌드 해 보시면 정상적으로 빌드가 되는 것을 확인할 수 있습니다.

~~~sh
git clone https://github.com/RockyLim92/linux-3.10-artik
~~~

**Comment by RockyLim92** [comment]
빠진 다른 파일도 있어서 확인중 입니다. 확인 후 다시 공지 해 드리겠습니다.

**Comment by RockyLim92** [comment]
빠진 파일들 전부 추가하여 업데이트 하였습니다. 아울러, 정상적으로 빌드가 되는 것까지 다시 한 번 확인하였습니다.

감사합니다.
